name: CI Format

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # using example 1 from https://github.com/creyD/prettier_action
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write *.md
